#!/usr/bin/env perl
use strict;
use warnings;
use File::Slurp qw/read_file/;

my $file = $ARGV[0];
my @lines = read_file($file);

my $selection = $lines[int(rand(@lines))];
chomp $selection;

print "$selection\n";
